#!/usr/bin/env bash

rm -rf dist
mkdir -p dist
rm -rf bin
mkdir -p bin

echo "transpile livescript in src to dist ..."
./node_modules/.bin/lsc -co dist --no-header src 
echo "build src/ngxgen.ls -> bin/ngxgen.js ..."
echo "#!/usr/bin/env node" > bin/ngxgen.js
./node_modules/.bin/lsc -cp --no-header src/ngxgen.ls >> bin/ngxgen.js
chmod 755 bin/ngxgen.js

echo "copy src/config.ngx to dist ..."
cp src/config.ngx dist
echo "done."


