// Generated by LiveScript 1.6.0
(function(){
  var route, provider, providers, designate;
  route = require('./route');
  provider = require('./provider');
  providers = require('./providers');
  designate = require('./designate');
  module.exports = {
    route: route,
    provider: provider,
    providers: providers,
    designate: designate
  };
}).call(this);
