// Generated by LiveScript 1.6.0
(function(){
  var nodeFetch, lderror, yauzl, pthk, tar, semver, fs, fetch, getVersionType, provider, ref$;
  nodeFetch = require('node-fetch');
  lderror = require('lderror');
  yauzl = require('yauzl');
  pthk = require('pthk');
  tar = require('tar');
  semver = require('@plotdb/semver');
  fs = require("fs-extra");
  fetch = nodeFetch;
  getVersionType = function(v){
    if (v === 'main') {
      return 'main';
    } else if (v === 'latest') {
      return 'latest';
    } else if (/^\d+\.\d+\.\d+$/.test(v)) {
      return 'specific';
    } else if (/^[~^>]/.test(v) && semver.validRange(v)) {
      return 'range';
    } else {
      return null;
    }
  };
  provider = function(o){
    o == null && (o = {});
    this._name = o.name || "unnamed" + (provider._idx++);
    this._ps = [].concat(o.chain || []);
    this._fetchRealVersion = o.fetchRealVersion;
    this._fetchBundleFile = o.fetchBundleFile;
    this._fetchVersionList = o.fetchVersionList;
    this._check = o.check;
    this._opt = o.opt || {};
    return this;
  };
  provider._hash = {};
  provider._idx = 0;
  provider.add = function(p){
    return this._hash[p._name] = p;
  };
  provider.get = function(n){
    return this._hash[n];
  };
  provider.versionType = getVersionType;
  provider.prototype = (ref$ = Object.create(Object.prototype), ref$.opt = function(o){
    return this._opt = o || {};
  }, ref$.fetch = function(o){
    var this$ = this;
    o == null && (o = {});
    return Promise.resolve().then(function(){
      var path, root, name, version, force, cachetime, versionType, params, _;
      path = {
        base: {}
      };
      root = o.root, name = o.name, version = o.version, force = o.force, cachetime = o.cachetime;
      cachetime = cachetime || 60 * 60;
      versionType = getVersionType(version);
      if (!versionType) {
        return lderror.reject(400, "incorrect version-type when accessing " + name + "@" + version);
      }
      if (versionType === 'range' || versionType === 'latest') {
        return lderror.reject(400, versionType + " version should be resolved before fetch");
      }
      if ((name + "").length > 128 || (version + "").length > 40) {
        return lderror.reject(998);
      }
      params = {
        path: path,
        versionType: versionType,
        root: root,
        name: name,
        version: version,
        force: force,
        cachetime: cachetime
      };
      if (!/^(?:@[0-9a-z._-]+\/)?[0-9a-z._-]+$/.test(name)) {
        return lderror.reject(400);
      }
      path.base.pkg = pthk.join(root, pthk.rectify(name));
      path.base.version = pthk.join(path.base.pkg, version);
      path.version = pthk.join(path.base.version, '.reg.version');
      path[404] = pthk.join(path.base.version, '.reg.404');
      if (versionType === 'main') {
        return this$._fetchMain(params);
      }
      _ = function(idx){
        var pr, p;
        idx == null && (idx = -1);
        if (idx >= 0) {
          if (!(pr = this$._ps[idx])) {
            return lderror.reject(404);
          }
          p = pr.check({
            name: name,
            version: version
          }).then(function(){
            return pr._fetch(params);
          });
        } else {
          p = this$.check({
            name: name,
            version: version
          }).then(function(){
            if (!this$._fetchRealVersion) {
              return lderror.reject(404);
            } else {
              return this$._fetch(params);
            }
          });
        }
        return p['catch'](function(e){
          var id;
          return (id = lderror.id(e)) !== 404
            ? Promise.reject(e)
            : _(idx + 1);
        });
      };
      return _()['catch'](function(e){
        var id;
        if (!((id = lderror.id(e)) === 403 || id === 404 || id === 998)) {
          return Promise.reject(e);
        }
        if (id === 998) {
          return lderror.reject(404);
        }
        return fs.ensureDir(path.base.version).then(function(){
          return fs.writeFile(path[404], '');
        }).then(function(){
          return lderror.reject(404);
        });
      });
    });
  }, ref$.check = function(arg$){
    var name, version;
    name = arg$.name, version = arg$.version;
    if (this._check) {
      return this._check({
        name: name,
        version: version
      });
    } else {
      return Promise.resolve();
    }
  }, ref$.chain = function(ps){
    return this._ps.splice.apply(this._ps, [0, 0].concat(Array.isArray(ps)
      ? ps
      : [ps]));
  }, ref$._fetchMain = function(arg$){
    var root, name, version, force, cachetime, path, this$ = this;
    root = arg$.root, name = arg$.name, version = arg$.version, force = arg$.force, cachetime = arg$.cachetime, path = arg$.path;
    return Promise.resolve().then(function(){
      return fs.lstat(path.base.version)['catch'](function(){
        return null;
      });
    }).then(function(s){
      if (s && !force) {
        return lderror.reject(998);
      }
      return this$.resolveLatest({
        root: root,
        name: name,
        cachetime: cachetime,
        force: force
      }).then(function(v){
        return this$.designate({
          root: root,
          name: name,
          version: v,
          cachetime: cachetime
        });
      });
    });
  }, ref$.resolveLatest = function(o){
    var this$ = this;
    o == null && (o = {});
    return Promise.resolve().then(function(){
      var root, name, force, cachetime, base, peek, _;
      root = o.root, name = o.name, force = o.force, cachetime = o.cachetime;
      cachetime = cachetime || 60 * 60;
      if ((name + "").length > 128) {
        return lderror.reject(404);
      }
      if (!/^(?:@[0-9a-z._-]+\/)?[0-9a-z._-]+$/.test(name)) {
        return lderror.reject(400);
      }
      base = pthk.join(root, pthk.rectify(name));
      peek = function(pvd){
        var file;
        if (!pvd._fetchRealVersion) {
          return lderror.reject(404);
        }
        file = pthk.join(base, ".reg.latest." + pvd._name);
        return Promise.resolve().then(function(){
          if (force) {
            return null;
          }
          return fs.exists(file).then(function(isExisted){
            if (!isExisted) {
              return null;
            }
            return fs.stat(file).then(function(s){
              if (Date.now() > s.mtime.getTime() + cachetime * 1000) {
                return null;
              }
              return fs.readFile(file).then(function(r){
                return JSON.parse(r);
              });
            });
          });
        }).then(function(cached){
          if (cached) {
            return cached.version;
          }
          return pvd._fetchRealVersion({
            root: root,
            name: name,
            cachetime: cachetime,
            version: 'latest',
            versionType: 'latest'
          }).then(function(info){
            return fs.ensureDir(base).then(function(){
              return fs.writeFile(file, JSON.stringify({
                version: info.version
              }));
            }).then(function(){
              return info.version;
            });
          });
        });
      };
      _ = function(idx){
        var pvd;
        idx == null && (idx = -1);
        pvd = idx < 0
          ? this$
          : this$._ps[idx];
        if (!pvd) {
          return lderror.reject(404);
        }
        return pvd.check({
          name: name,
          version: 'latest'
        }).then(function(){
          return peek(pvd);
        })['catch'](function(e){
          if (lderror.id(e) !== 404) {
            return Promise.reject(e);
          } else {
            return _(idx + 1);
          }
        });
      };
      return _()['catch'](function(e){
        if (lderror.id(e) === 403) {
          return lderror.reject(404);
        } else {
          return Promise.reject(e);
        }
      });
    });
  }, ref$.designate = function(o){
    var this$ = this;
    o == null && (o = {});
    return Promise.resolve().then(function(){
      var root, name, version, cachetime, base, ref$, mainPath, tmp;
      root = o.root, name = o.name, version = o.version, cachetime = o.cachetime;
      if (getVersionType(version) !== 'specific') {
        return lderror.reject(400, "designate requires a specific version");
      }
      if ((name + "").length > 128 || (version + "").length > 40) {
        return lderror.reject(404);
      }
      if (!/^(?:@[0-9a-z._-]+\/)?[0-9a-z._-]+$/.test(name)) {
        return lderror.reject(400);
      }
      base = pthk.join(root, pthk.rectify(name));
      ref$ = [pthk.join(base, 'main'), pthk.join(base, ".main." + process.pid + ".tmp")], mainPath = ref$[0], tmp = ref$[1];
      return Promise.resolve().then(function(){
        return fs.exists(pthk.join(base, version, '.reg.version')).then(function(isExisted){
          if (isExisted) {
            return;
          }
          return this$.fetch({
            root: root,
            name: name,
            version: version,
            force: false,
            cachetime: cachetime
          });
        });
      }).then(function(){
        return fs.lstat(mainPath)['catch'](function(){
          return null;
        });
      }).then(function(s){
        return Promise.resolve().then(function(){
          if (s && !s.isSymbolicLink()) {
            return fs.remove(mainPath);
          }
        }).then(function(){
          return fs.remove(tmp);
        }).then(function(){
          return fs.symlink(version, tmp);
        }).then(function(){
          return fs.rename(tmp, mainPath);
        });
      }).then(function(){
        return {
          name: name,
          version: version
        };
      });
    });
  }, ref$.resolve = function(o){
    var this$ = this;
    o == null && (o = {});
    return Promise.resolve().then(function(){
      var root, name, version, force, cachetime, base, list, _;
      root = o.root, name = o.name, version = o.version, force = o.force, cachetime = o.cachetime;
      cachetime = cachetime || 60 * 60;
      if (getVersionType(version) !== 'range') {
        return lderror.reject(400, "not a range version: " + name + "@" + version);
      }
      if ((name + "").length > 128 || (version + "").length > 40) {
        return lderror.reject(404);
      }
      if (!/^(?:@[0-9a-z._-]+\/)?[0-9a-z._-]+$/.test(name)) {
        return lderror.reject(400);
      }
      base = pthk.join(root, pthk.rectify(name));
      list = function(pvd){
        var file;
        if (!pvd._fetchVersionList) {
          return lderror.reject(404);
        }
        file = pthk.join(base, ".reg.versions." + pvd._name);
        return Promise.resolve().then(function(){
          if (force) {
            return null;
          }
          return fs.exists(file).then(function(isExisted){
            if (!isExisted) {
              return null;
            }
            return fs.stat(file).then(function(s){
              if (Date.now() > s.mtime.getTime() + cachetime * 1000) {
                return null;
              }
              return fs.readFile(file).then(function(r){
                return JSON.parse(r);
              });
            });
          });
        }).then(function(cached){
          if (cached) {
            return cached.versions;
          }
          return pvd._fetchVersionList({
            name: name
          })['catch'](function(e){
            if (lderror.id(e) === 404) {
              return [];
            } else {
              return Promise.reject(e);
            }
          }).then(function(vs){
            return fs.ensureDir(base).then(function(){
              return fs.writeFile(file, JSON.stringify({
                versions: vs
              }));
            }).then(function(){
              return vs;
            });
          });
        });
      };
      _ = function(idx){
        var pvd;
        idx == null && (idx = -1);
        pvd = idx < 0
          ? this$
          : this$._ps[idx];
        if (!pvd) {
          return lderror.reject(404);
        }
        return pvd.check({
          name: name,
          version: version
        }).then(function(){
          return list(pvd);
        }).then(function(vs){
          var v;
          if (v = semver.maxSatisfying(vs, version)) {
            return v;
          }
          return lderror.reject(404);
        })['catch'](function(e){
          if (lderror.id(e) !== 404) {
            return Promise.reject(e);
          } else {
            return _(idx + 1);
          }
        });
      };
      return _()['catch'](function(e){
        if (lderror.id(e) === 403) {
          return lderror.reject(404);
        } else {
          return Promise.reject(e);
        }
      });
    });
  }, ref$._fetch = function(params){
    var root, name, version, cachetime, force, path, versionType, this$ = this;
    root = params.root, name = params.name, version = params.version, cachetime = params.cachetime, force = params.force, path = params.path, versionType = params.versionType;
    return Promise.resolve().then(function(){
      if (force) {
        return;
      }
      return fs.exists(path.version).then(function(isExisted){
        if (!isExisted) {
          return fs.exists(path[404]).then(function(is404){
            if (!is404) {
              return true;
            }
            return fs.stat(path[404]).then(function(s){
              var dirty;
              dirty = Date.now() > s.mtime.getTime() + cachetime * 1000;
              return !dirty
                ? false
                : fs.remove(path[404]).then(function(){
                  return true;
                });
            });
          });
        }
        return false;
      }).then(function(isDirty){
        if (!isDirty) {
          return lderror.reject(998);
        }
      });
    }).then(function(){
      return this$._fetchRealVersion(params).then(function(remoteInfo){
        return Promise.resolve().then(function(){
          return fs.remove(path.base.version);
        }).then(function(){
          return fs.ensureDir(path.base.version);
        }).then(function(){
          return fs.writeFile(path.version, JSON.stringify(remoteInfo));
        }).then(function(){
          return remoteInfo;
        });
      });
    }).then(function(remoteInfo){
      return this$._fetchBundleFile(import$({
        remoteInfo: remoteInfo
      }, params));
    });
  }, ref$);
  if (typeof module != 'undefined' && module !== null) {
    module.exports = provider;
  } else if (typeof window != 'undefined' && window !== null) {
    window.registry = provider;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
